apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  client:
    preferService: true
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    security:
      admin_user: "admin"
      admin_password: "admin"
    # auth:
    #   disable_login_form: False
    #   disable_signout_menu: True
    auth.anonymous:
      enabled: True
  service:
    name: "grafana"
    labels:
      app: "grafana"
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [grafana] }
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-operated
  namespace: monitoring
  labels:
    app: grafana
spec:
  name: prometheus
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-operated.prometheus:9090
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"