apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 10s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/prometheus-operator/kube-prometheus.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  force: false
  interval: 10s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator