apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 10s
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/grafana-operator/grafana-operator.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  force: false
  interval: 10s
  path: ./deploy/manifests/latest
  prune: true
  sourceRef:
    kind: GitRepository
    name: grafana-operator