apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: operators
  namespace: flux-system
spec:
  interval: 10s
  path: ./devops/colima/infra/operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: kepler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  dependsOn:
  - name: operators
  interval: 10s
  path: ./devops/colima/infra/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: kepler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tidb
  namespace: flux-system
spec:
  dependsOn:
  - name: operators
  interval: 10s
  path: ./devops/colima/infra/tidb
  prune: true
  sourceRef:
    kind: GitRepository
    name: kepler