apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: operators
spec:
  channel: v4
  name: grafana-operator
  source: operatorhubio-catalog
  sourceNamespace: olm