apiVersion: v1
kind: Namespace
metadata:
  name: operator-spark
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: operator-spark
spec:
  targetNamespaces:
  - default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spark-gcp
  namespace: operator-spark
spec: 
  channel: alpha
  name: spark-gcp
  source: operatorhubio-catalog
  sourceNamespace: olm