apiVersion: v1
kind: Namespace
metadata:
  name: operator-prometheus
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: operator-prometheus
spec:
  targetNamespaces:
  - monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: operator-prometheus
spec: 
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: olm