apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: spark
  namespace: operators
spec:
  interval: 1m0s
  url: https://googlecloudplatform.github.io/spark-on-k8s-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark
  namespace: operators
spec:
  chart:
    spec:
      chart: spark-operator
      sourceRef:
        kind: HelmRepository
        name: spark
      version: 1.1.26
  interval: 1m0s