name: Release
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: Jtalk/setup-sbt@v2
        with:
          version: 1.8.0
      - run: sbt "project devops" run
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - run: |
              cp -r target/colima devops/colima/snapshot/$(date +%s)
              cp -r target/colima/ devops/colima/latest
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'devops/colima'
          push: true
          message: 'ci'
          committer_name: bot
          committer_email: bot@noreply.com

