name: DevOps
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Sbt
        uses: Jtalk/setup-sbt@v2
        with:
          version: 1.8.0
      - name: Run Sbt
        run: sbt "project devops" run
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Move File
        run: |
              cp -r target/colima devops/colima/snapshot/$(date +%s)
              cp -r target/colima/ devops/colima/latest
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'devops/colima'
          message: 'ci'
          committer_name: bot
          committer_email: bot@noreply.com
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

